#!/bin/bash

RUN_DIR=/var/vcap/sys/run/nginx
LOG_DIR=/var/vcap/sys/log/nginx
UPLOADS_DIR=/var/vcap/data/webapp/tmp/uploads
STAGED_UPLOADS_DIR=/var/vcap/data/webapp/tmp/staged_droplet_uploads
PIDFILE=$RUN_DIR/nginx.pid
RACKAPP_PACKAGE_DIR=/var/vcap/packages/rackapp
RACKAPP_JOB_DIR=/var/vcap/jobs/webapp

source /var/vcap/packages/common/utils.sh
redirect_output 'nginx'

case $1 in

  start)
    pid_guard $PIDFILE "Nginx"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    if [ ! -d "$UPLOADS_DIR" ]
    then
      mkdir -p $UPLOADS_DIR
    fi

    if [ ! -d "$STAGED_UPLOADS_DIR" ]
    then
      mkdir -p $STAGED_UPLOADS_DIR
    fi

    exec /var/vcap/packages/nginx_next/sbin/nginx \
         -c /var/vcap/jobs/webapp/config/nginx.conf \
         >>$LOG_DIR/nginx.stdout.log \
         2>>$LOG_DIR/nginx.stderr.log

    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: nginx_ctl {start|stop}"

    ;;

esac
