#!/usr/bin/env bash

# Lists all *.log files for jobs and monit

set -e # exit immediately if a simple command exits with a non-zero status
set -u # report the usage of uninitialized variables

cd $(dirname $0)/..
release_path=$(pwd)
scripts=${release_path}/scripts

# TODO - add package's **/*.log too (e.g. webapps)

log_dir=/var/vcap/sys/log
mkdir -p ${log_dir}
find ${log_dir} -name "*.log"
