#!/usr/bin/env ruby

# Prints an ordered list of packages to be installed, based on their dependencies

require "yaml"

# FIXME - this list below isn't ordered; needs ordering
# latest_dev_release = `ls -ct dev_releases/*-dev.yml`.lines.first.strip
# latest_dev_release_yaml = YAML.load_file(latest_dev_release)
# packages = latest_dev_release_yaml["packages"]
# packages.map {|p| puts p["name"]}

%w[common libpq mysqlclient nginx sqlite ruby rackapp].each {|p| puts p}
