#!/bin/bash

# Control script to start/stop ruby/rack RedisLive job on a BOSH controlled VM

RUN_DIR=/var/vcap/sys/run/RedisLive
LOG_DIR=/var/vcap/sys/log/RedisLive
STORE=/var/vcap/store/RedisLive
PIDFILE=$RUN_DIR/RedisLive.pid

export PATH=/var/vcap/packages/python27/bin:$PATH

HOME=${HOME:-/home/vcap}

source /var/vcap/packages/common/utils.sh
redirect_output 'redislive-monitor'


case $1 in

  start)
    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    mkdir -p $STORE

    echo $$ > $PIDFILE

    cd /var/vcap/packages/RedisLive/

    exec ./redis-monitor.py --duration=120 \
                   >>$LOG_DIR/redislive_monitor.stdout.log \ 
                  2>>$LOG_DIR/redislive_monitor.stderr.log
    ;;

  stop)
    kill_and_wait $PIDFILE
    ;;

  logs)
    cat $LOG_DIR/*
    ;;

  tail)
    tail -f $LOG_DIR/*
    ;;

  clearlogs)
    rm $LOG_DIR/*
    ;;

  *)
  echo "Usage: RedisLive_ctl {start|stop|logs|tail|clearlogs}" ;;
esac
exit 0
