---
jobs:
  - webapp
  - postgres
properties:
  description: "Todo app: puma, migrations and postgresql"
  webapp:
    package: todo
    use_nginx: 1
    run_migrations: 1
    appstack: puma
  postgres:
    host: 127.0.0.1
    user: todo
    password: p03tgR3s
    database: todo