#!/bin/bash

RUN_DIR=/var/vcap/sys/run/phpfpm
LOG_DIR=/var/vcap/sys/log/phpfpm
UPLOADS_DIR=/var/vcap/data/phpfpm/tmp/uploads
PIDFILE=$RUN_DIR/nginx.pid

source /var/vcap/packages/common/utils.sh
redirect_output 'nginx-phpfpm'

case $1 in

  start)
    pid_guard $PIDFILE "Nginx"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    if [ ! -d "$UPLOADS_DIR" ]
    then
      mkdir -p $UPLOADS_DIR
    fi

    exec /var/vcap/packages/nginx_next/sbin/nginx \
         -c /var/vcap/jobs/phpfpm/config/nginx.conf \
         >>$LOG_DIR/nginx.stdout.log \
         2>>$LOG_DIR/nginx.stderr.log

    ;;

  stop)
    echo "Stopping nginx"
    kill_and_wait $PIDFILE
    ;;

  *)
    echo "Usage: nginx_ctl {start|stop}"

    ;;

esac
