#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 1>&2
  exit 1
fi

cd $(dirname $0)/..
release_path=$(pwd)

# apt-get update
apt-get install -y --force-yes patch g++ libxml2-dev libxslt-dev libpq-dev git-core

gem install bundler rake --no-ri --no-rdoc
cd /bosh
rake bundle_install
rake build

cd ${release_path}