#!/usr/bin/env bash

set -x

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 1>&2
  exit 1
fi

cd $(dirname $0)/..
release_path=$(pwd)

apt-get update
apt-get install -y --force-yes build-essential flex bison upstart runit patch g++ libxml2-dev \
  libxslt-dev libpq-dev git-core libsqlite3-dev vim curl || exit 1

bosh_users_password=vcap
/usr/sbin/addgroup --system admin
/usr/sbin/adduser --disabled-password --gecos Ubuntu vcap
echo \"vcap:${bosh_users_password}\" | /usr/sbin/chpasswd
echo \"root:${bosh_users_password}\" | /usr/sbin/chpasswd

for grp in admin adm audio cdrom dialout floppy video plugdev dip
do
  /usr/sbin/adduser vcap $grp
done

if [[ -x /var/vcap/bosh/bin/monit ]]
then
  /var/vcap/bosh/bin/monit -V
else
  export build_dir=/bosh/agent/misc/stemcell/build2/
  work_path="/"
  export chroot="/"
  ${build_dir}/stages/bosh_monit/apply.sh ${work_path}
fi

gem install bundler rake --no-ri --no-rdoc
cd /bosh
rake bundle_install
rake build
gem install webmock --no-ri --no-rdoc

mkdir -p /var/vcap/bosh
chmod 775 /var/vcap/bosh
chown -R vcap:vcap /var/vcap

cd ${release_path}