#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: This script must be run as root" 1>&2
  exit 1
fi

cd $(dirname $0)/..
release_path=$(pwd)

apt-get update
apt-get install -y --force-yes flex bison upstart runit patch g++ libxml2-dev libxslt-dev libpq-dev git-core || exit 1

build_dir=/bosh/agent/misc/stemcell/build2/
work_path="/"
export chroot="/"
if [[ -x /var/vcap/bosh/bin/monit ]]
then
  /var/vcap/bosh/bin/monit -V
else
  ${build_dir}/stages/bosh_users/apply.sh ${work_path}
  ${build_dir}/stages/bosh_monit/apply.sh ${work_path}
fi

gem install bundler webmock rake --no-ri --no-rdoc
cd /bosh
rake bundle_install
rake build

chmod 775 /var/vcap
chmod 775 /var/vcap/bosh
chown -R vcap:vcap /var/vcap

cd ${release_path}