#!/usr/bin/env bash

set -x

base_dir=/var/vcap
jobs_dir=${base_dir}/data/jobs

cd $(dirname $0)/..
release_path=$(pwd)
scripts=${release_path}/scripts

sudo chpst -u vcap:vcap ${scripts}/helpers/start_monit

sudo chown vcap:vcap -r /var/vcap

echo "tail -f /var/vcap/monit/monit.log  # monit log"