#!/usr/bin/env bash

set -e # exit immediately if a simple command exits with a non-zero status
set -u # report the usage of uninitialized variables

base_dir=/var/vcap
${base_dir}/bosh/bin/monit stop all