#!/usr/bin/env bash

# Iterates through each examples/*yml to ensure that it is a valid example for this boshrelease;
# or that the bosh release still works against all expected examples.

set -e # exit immediately if a simple command exits with a non-zero status
set -u # report the usage of uninitialized variables

[ "$(whoami)" != 'root' ] && ( echo ERROR: run as root user; exit 1 )

cd $(dirname $0)/..
release_path=$(pwd)
scripts=${release_path}/scripts

examples=$(ls -R ${release_path}/examples/*.yml)

echo "|"
echo "| Stopping any existing jobs"
echo "|"
${scripts}/stop

for example in ${examples}
do
  echo "|"
  echo "| Testing configuration template rendering:"
  echo "| * ${example}"
  echo "|"
  ${scripts}/configure ${example}
done

for example in ${examples}
do
  echo "|"
  echo "| Testing full update & start sequences:"
  echo "| * ${example}"
  echo "|"
  ${scripts}/update ${example}
done