#!/usr/bin/env bash

# Updates to latest BOSH release (dev_builds)
#
# 1. If a package has a new version, then package installed
# 2. If a job has a new version, then job templates rendered
# 3. Jobs (monit) restarted

set -e # exit immediately if a simple command exits with a non-zero status
set -u # report the usage of uninitialized variables

# Currently, see Rakefile "rake update"