#!/usr/bin/env bash

# Updates to latest BOSH release (dev_builds)
#
# 1. Stop all jobs (script/stop)
# 2. Install packages (script/install)
# 3. Render templates (script/configure MANIFEST)
# 4. Start all jobs (script/start)

set -e # exit immediately if a simple command exits with a non-zero status
set -u # report the usage of uninitialized variables

cd $(dirname $0)/..
release_path=$(pwd)
scripts=${release_path}/scripts

base_dir=/var/vcap

manifest_path=${1:-UNKNOWNFILE}
if [[ ! -f ${manifest_path} ]]; then
  echo "USAGE: update MANIFEST_PATH"
  echo "  # MANIFEST_PATH - YAML file, contains 'properties' key."
  exit 1
fi

./scripts/stop
./scripts/install
./scripts/configure ${manifest_path}
./scripts/start